name: jupyterlite-lsp
channels:
  - conda-forge
  - nodefaults
dependencies:
  # build
  - nodejs >=18,<19
  - python >=3.8,<3.12
  - doit-with-toml
  - flit
  # lab
  - jupyterlab >=3.5,<4.0
  - jupyterlab-lsp >=3.10.2
  # lint
  - black
  - docformatter
  - isort
  - pydocstyle
  - ssort
  # docs
  - pydata-sphinx-theme
  - myst-nb
  - sphinx-copybutton
  # lite
  - pkginfo
  - pip
  - python-libarchive-c
  - jupyter-server-mathjax
  - pip:
      - jupyterlite ==0.1.0b15
